language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
matrix:
  allow_failures:
    - python: "3.7-dev"
before_install: true
install:
  - pip install -U pip
  - pip install -U setuptools
script: python setup.py test